name: coffeehouse
description: Official API wrapper for Intellivoid's Coffeehouse API.
version: 0.1.0
repository: https://github.com/intellivoid/CoffeeHouse-Dart-API-Wrapper
dependencies:
  http: ^0.12.2
environment:
  sdk: '>=2.1.0 <3.0.0'
